### ISSUE TITLE
 Error when a bot heals

### ISSUE THREAD

**Issue by MGDCl** [Bermiin/StrikeDeathMessages#3]
I don't know if this error is from the plugin or from Panda Spigot, but since the plugin name came out in the error I assumed that
[12:25:48 ERROR]: Could not pass event EntityDamageByEntityEvent to StrikeDeathMessages v0.1.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:557) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:470) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:589) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1117) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:739) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:512) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1099) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.attack(NMSImpl.java:230) ~[?:?]
        at net.citizensnpcs.util.NMS.attack(NMS.java:59) ~[?:?]
        at net.citizensnpcs.npc.ai.MCTargetStrategy$1.handle(MCTargetStrategy.java:291) ~[?:?]
        at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:138) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:446) ~[?:?]
        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:410) ~[?:?]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1773) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1740) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.tick(NMSImpl.java:1147) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:630) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:37) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:889) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:814) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:647) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_202]
        at me.bermine.sdm.listeners.PlayerListeners.onPlayerDeath(PlayerListeners.java:36) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-84]
        ... 35 more

**Comment by Bermiin** [comment]
Could you please try if its still happening on the latest release?

**Comment by MGDCl** [comment]
> Could you please try if its still happening on the latest release?

It is already resolved, thank you.
